server:
  port: 9001

spring:
  application:
    name: server

  datasource:
    username: root
    password: 31415926
    url: jdbc:mysql://localhost:3306/vivo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/