spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: server_api
          uri: lb://SERVER
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix=1

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
